### ISSUE TITLE
这个插件怎么用啊？

### ISSUE THREAD

**Issue by Wang-G17** [Philofallever/gracefulpoetry#1]
在vscode上下载后不知道怎么用。
就来这边问一下。

**Comment by Wang-G17** [comment]
看见侧边栏了。。

**Comment by FalleverX** [comment]
> 看见侧边栏了。。

哈哈~~

**Comment by FoilHao** [comment]
为什么我的侧边栏没有捏～

**Comment by FalleverX** [comment]
> 为什么我的侧边栏没有捏～

![image](https://user-images.githubusercontent.com/15180187/234476703-0ca5430e-4085-4e83-bfdc-47be3682e94c.png)
在资源管理器试图下  没有的话右键看看有没有条目

**Comment by FoilHao** [comment]
喔喔，找到了～ 非常感谢
